import assert from 'node:assert/strict';
import { test } from 'node:test';
import fs from 'node:fs/promises';
import path from 'node:path';
import os from 'node:os';
import { DatabaseSync } from 'node:sqlite';
import { git } from '../plugins/feature-theater/scripts/util.mjs';
import { runChecks, updateChecks } from '../plugins/feature-theater/scripts/verification.mjs';
import { initializeManagedProject, createFeature, recordCandidate, setFeatureStatus, updateSpec, getFeatureContext } from '../plugins/feature-theater/scripts/workspace.mjs';

test('latest required receipt and current specification gate delivery; dirty checks cannot pass', async t => {
  const workspace = await fs.mkdtemp(path.join(os.tmpdir(), 'theater-evidence-'));
  t.after(() => fs.rm(workspace, { recursive: true, force: true }));
  const args = { workspace_path: workspace, feature: 'alpha' };
  await initializeManagedProject({ workspace_path: workspace, project_name: 'Evidence', description: 'Exercise actual receipt gates.' });
  const lane = await createFeature({ ...args, title: 'Alpha', outcome: 'Verified behavior.', spec: '# Alpha\n\nThe README exists.' });
  const repo = lane.feature.checkoutPath;
  await fs.appendFile(path.join(repo, '.git', 'info', 'exclude'), '\n.check-fails\n');
  await updateChecks({ ...args, checks: [{ key: 'actual', purpose: 'Read the committed README and fixture state', argv: [process.execPath, '-e', "require('node:fs').readFileSync('README.md'); if (require('node:fs').existsSync('.check-fails')) process.exit(7)"] }] });
  assert.equal((await runChecks(args)).verification.ready, true);
  await recordCandidate({ ...args, summary: 'Ready.', checks: ['README receipt'] });
  await setFeatureStatus({ ...args, status: 'done' });
  await fs.writeFile(path.join(repo, '.check-fails'), 'fail');
  assert.equal((await runChecks(args)).verification.ready, false);
  await assert.rejects(recordCandidate({ ...args, summary: 'Stale pass.', checks: ['old receipt'] }), error => error.code === 'COMPLETION_NOT_PROVEN');
  await fs.rm(path.join(repo, '.check-fails'));
  assert.equal((await runChecks(args)).verification.ready, true);
  await recordCandidate({ ...args, summary: 'Ready again.', checks: ['current receipt'] });
  await setFeatureStatus({ ...args, status: 'done' });
  await updateSpec({ ...args, content: '# Alpha\n\nThe README must also describe startup.', rationale: 'New acceptance behavior.' });
  assert.equal((await getFeatureContext(args)).feature.status, 'active');
  await assert.rejects(recordCandidate({ ...args, summary: 'Old contract.', checks: ['old receipt'] }), error => error.code === 'COMPLETION_NOT_PROVEN');
  await updateChecks({ ...args, checks: [{ key: 'mutating', purpose: 'Detect a check that changes source', argv: [process.execPath, '-e', "require('node:fs').writeFileSync('unexpected.txt', 'mutated')"] }] });
  const changed = await runChecks(args);
  assert.equal(changed.receipts[0].passed, false);
  assert.match(changed.receipts[0].summary, /checkout changed/);
  assert.equal((await git(repo, 'status', '--porcelain')).stdout.includes('unexpected.txt'), true);
});

test('version-2 data migrates without turning historical claims into current proof', async t => {
  const workspace = await fs.mkdtemp(path.join(os.tmpdir(), 'theater-migration-'));
  t.after(() => fs.rm(workspace, { recursive: true, force: true }));
  const args = { workspace_path: workspace, feature: 'legacy' };
  await initializeManagedProject({ workspace_path: workspace, project_name: 'Legacy', description: 'Preserve history.' });
  const lane = await createFeature({ ...args, title: 'Legacy', outcome: 'Preserve historical work.', spec: '# Legacy\n\nOriginal intent.' });
  const db = new DatabaseSync(path.join(workspace, '.theater', 'state.sqlite3'));
  const feature = db.prepare('SELECT * FROM features WHERE slug = ?').get('legacy');
  db.prepare("INSERT INTO evidence(id, feature_id, kind, summary, revision, passed, created_at) VALUES ('old-evidence', ?, 'test', 'Previously reported pass', ?, 1, ?)").run(feature.id, lane.feature.baseRevision, new Date().toISOString());
  db.prepare("INSERT INTO candidates(id, feature_id, revision, base_revision, summary, checks_json, status, created_at) VALUES ('old-candidate', ?, ?, ?, 'Old accepted candidate', '[]', 'accepted', ?)").run(feature.id, lane.feature.baseRevision, lane.feature.baseRevision, new Date().toISOString());
  db.prepare("UPDATE features SET status = 'done' WHERE id = ?").run(feature.id);
  for (const column of ['source', 'spec_revision', 'contract_hash', 'check_key', 'argv_json', 'exit_code', 'output', 'duration_ms']) db.exec(`ALTER TABLE evidence DROP COLUMN ${column}`);
  for (const column of ['spec_revision', 'contract_hash']) db.exec(`ALTER TABLE candidates DROP COLUMN ${column}`);
  db.exec("UPDATE meta SET value = '2' WHERE key = 'schema_version'");
  db.close();
  const context = await getFeatureContext(args);
  assert.equal(context.feature.status, 'active');
  assert.equal(context.candidates[0].status, 'superseded');
  assert.equal(context.evidence[0].source, 'reported');
  assert.equal(context.verification.ready, false);
  await fs.writeFile(path.join(workspace, '.theater', 'features', 'legacy', 'spec.md'), 'STALE PROJECTION');
  await getFeatureContext(args);
  assert.match(await fs.readFile(path.join(workspace, '.theater', 'features', 'legacy', 'spec.md'), 'utf8'), /Original intent/);
});
